services:
  - type: web
    name: n8n
    env: image
    image:
      url: docker.io/n8nio/n8n:latest
    plan: starter
    envVars:
      - key: PORT
        value: "5678"
      - key: N8N_PORT
        value: "5678"
      - key: NODE_OPTIONS
        value: "--max-old-space-size=400"
      - key: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
        value: "false"
